### ISSUE TITLE
Classes and Inheritance

### ISSUE THREAD

**Issue by dhilln** [caramel-language/caramel-documentation#3]
Classes are very commonly used in modern, object-oriented programming languages such as JavaScript, Swift, Scala, Python, and Dart. As such, it would make the language rather limiting if they were not included in Caramel. 

## Syntax
Classes are defined using the keyword `class` and then surrounding the resulting code in braces like so.

```swift
class Person {
    // code here ...
}
```

Obviously classes would not be powerful without being able to inherit from other classes, in order to build a larger class from smaller parent/subclasses. Class inheritance would be performed using the `extends` keyword, like in Java. Classes that inherit/extend from other classes can also override their methods.

```swift
class Animal {
    // animal base code here ..
    func isPredator(): bool { return false }
}

class Cat extends Animal {
    // cats are predators
    override func isPredator(): bool { return true }
}
```

**Comment by harrego** [comment]
It has been decided by myself and @dhilln that a constructor will also be included. This is also a look into how variables will sit in classes.

## Syntax

```
class Person {
    var name: string = ""

    init(name: string) {
        self.name = name
    }
}
```

**Comment by harrego** [comment]
#4 added these features
